ALTER TABLE category
CHANGE COLUMN category_id id INT(11) NOT NULL AUTO_INCREMENT,
CHANGE COLUMN category_title title VARCHAR(45) NULL DEFAULT NULL;

ALTER TABLE product
CHANGE COLUMN product_id id INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN product_title title VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN product_description description VARCHAR(255) NULL DEFAULT NULL ,
CHANGE COLUMN product_image image VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN product_price price INT(11) NULL DEFAULT NULL;
